const employee = {
  id: '',
  fullName: '',
  lastName: '',
  designation: '',
  perDayWages: '',
  primaryContactNo: '',
  secondaryContactNo: '',
  imageLink: '',
  emailId: '',
  aadharCardNo: '',
  panCardNo: '',
  address: '',
  pinCode: '',
  country: '',
  state: '',
  orgId: '',
  status: '',
  createdDateTime: '',
};
