const user = {
  id: '',
  firstName: '',
  lastName: '',
  emailId: '',
  password: '',
  primaryContactNo: '',
  lastLoginDate: '',
  lastLoginDateDisplay: '',
  role: '',
  authorities: '',
  orgId: '',
  updatedDateTime: '',
  createdDateTime: '',
};
