import { API } from 'bckend';

export const url = {
  profile: {
    CREATE_PROFILE_URL: '/profile/api/v1/profile/create',
    GET_ALL_PROFILE_URL: '/profile/api/v1/admin/profile/list',
    GET_MONTH_PROFILE_LIST_URL: '/profile/api/v1/admin/profile/month',
    GET_PROFILE_URL: '/profile/api/v1/profile/',
    DELETE_PROFILE_URL: '/profile/api/v1/profile/delete/',
    UPDATE_PROFILE_URL: '/profile/api/v1/profile/update/',
  },
  user: {
    LOGIN_URL: '/user/api/v1/public/user/login',
    CREATE_USER_URL: '/user/api/v1/user/create',
    GET_ALL_USER_URL: '/user/api/v1/user/list',
    CHANGE_PASSWORD_URL: '/user/api/v1/user/change-password/',
    FORGET_PASSWORD_URL: '/user/api/v1/public/user/forget-password',
    GET_USER_URL: '/user/api/v1/user/',
    DELETE_USER_URL: '/user/api/v1/user/delete/',
    UPDATE_USER_URL: '/user/api/v1/user/update/',
  },
  client: {
    ADD_CLIENT_URL: `${API}/client/api/v1/client/add`,
    UPDATE_CLIENT_URL: `${API}/client/api/v1/client/update/`,
    DELETE_CLIENT_URL: `${API}/client/api/v1/client/delete/`,
    GET_CLIENT_URL: `${API}/client/api/v1/client/`,
    GET_ALL_CLIENT_URL: `${API}/client/api/v1/client/list/`,
    GET_MONTH_CLIENT_LIST_URL: `${API}/client/api/v1/client/date/`,
    GET_ALL_CLIENT_KEY_VALUE_URL: `${API}/client/api/v1/client/list/key-value/`,
  },
  employee: {
    ADD_EMPLOYEE_URL: `${API}/employee/api/v1/employee/add`,
    UPDATE_EMPLOYEE_URL: `${API}/employee/api/v1/employee/update/`,
    DELETE_EMPLOYEE_URL: `${API}/employee/api/v1/employee/delete/`,
    GET_EMPLOYEE_URL: `${API}/employee/api/v1/employee/`,
    GET_ALL_EMPLOYEE_URL: `${API}/employee/api/v1/employee/list/`,
    GET_MONTH_EMPLOYEE_LIST_URL: `${API}/employee/api/v1/employee/date/`,
    GET_ALL_EMPLOYEE_KEY_VALUE_URL: `${API}/employee/api/v1/employee/list/key-value/`,
  },
  product: {
    ADD_PRODUCT_URL: `${API}/product/api/v1/product/add`,
    UPDATE_PRODUCT_URL: `${API}/product/api/v1/product/update/`,
    DELETE_PRODUCT_URL: `${API}/product/api/v1/product/delete/`,
    GET_PRODUCT_URL: `${API}/product/api/v1/product/`,
    GET_ALL_PRODUCT_URL: `${API}/product/api/v1/product/list/`,
    UPDATE_PRODUCT_QUANTITY_URL: `${API}/product/api/v1/product-stock/update/stock/`,
  },

  material: {
    ADD_MATERIAL_URL: `${API}/material/api/v1/material/add`,
    UPDATE_MATERIAL_URL: `${API}/material/api/v1/material/update/`,
    UPDATE_MATERIAL_STOCK_URL: `${API}/material/api/v1/material/update/stock/`,
    DELETE_MATERIAL_URL: `${API}/material/api/v1/material/delete/`,
    GET_MATERIAL_URL: `${API}/material/api/v1/material/`,
    GET_ALL_MATERIAL_URL: `${API}/material/api/v1/material/list/`,
  },
  vendor: {
    ADD_VENDOR_URL: `${API}/vendor/api/v1/vendor/add`,
    UPDATE_VENDOR_URL: `${API}/vendor/api/v1/vendor/update/`,
    DELETE_VENDOR_URL: `${API}/vendor/api/v1/vendor/delete/`,
    GET_VENDOR_URL: `${API}/vendor/api/v1/vendor/`,
    GET_ALL_VENDOR_URL: `${API}/vendor/api/v1/vendor/list/`,
    GET_MONTH_VENDOR_LIST_URL: `${API}/vendor/api/v1/vendor/date/`,
    GET_ALL_VENDOR_KEY_VALUE_URL: `${API}/vendor/api/v1/vendor/list/key-value/`,
  },
  expense: {
    ADD_EXPENSE_URL: `${API}/expense/api/v1/expense/add`,
    UPDATE_EXPENSE_URL: `${API}/expense/api/v1/expense/update/`,
    DELETE_EXPENSE_URL: `${API}/expense/api/v1/expense/delete/`,
    GET_EXPENSE_URL: `${API}/expense/api/v1/expense/`,
    GET_ALL_EXPENSE_URL: `${API}/expense/api/v1/expense/list/`,
    GET_MONTH_EXPENSE_LIST_URL: `${API}/expense/api/v1/expense/date/`,
  },
  order: {
    ADD_ORDER_URL: `${API}/order/api/v1/order/add`,
    UPDATE_ORDER_URL: `${API}/order/api/v1/order/update/`,
    DELETE_ORDER_URL: `${API}/order/api/v1/order/delete/`,
    GET_ORDER_URL: `${API}/order/api/v1/order/`,
    GET_ALL_ORDER_URL: `${API}/order/api/v1/order/list/`,
    GET_MONTH_ORDER_LIST_URL: `${API}/order/api/v1/order/date/`,
  },
  production: {
    UPDATE_PRODUCTION_URL: `${API}/api/v1/production/update/status`,
    GET_ALL_PRODUCTION_URL: `${API}/api/v1/production/list/`,
  },
  salary: {
    ADD_SALARY_URL: `${API}/employee/api/v1/salary/paid`,
    GET_ALL_SALARY_URL: `${API}/employee/api/v1/salary/list/`,
  },
  advance_salary: {
    ADD_ADVANCE_SALARY_URL: `${API}/employee/api/v1/advance/paid-advance`,
    GET_ALL_ADVANCE_SALARY_URL: `${API}/employee/api/v1/advance/list/`,
  },
  purchase_product: {
    ADD_PURCHASE_PRODUCT_URL: `${API}/purchase/api/v1/purchase-product/add`,
    GET_ALL_PURCHASE_PRODUCT_URL: `${API}/purchase/api/v1/purchase-product/list/`,
    GET_PURCHASE_PRODUCT_URL: `${API}/purchase/api/v1/purchase-product/`,
  },
  sell_product: {
    ADD_ADVANCE_SALARY_URL: `${API}/employee/api/v1/purchase-product/add`,
    GET_ALL_PURCHASE_PRODUCT_URL: `${API}/employee/api/v1/purchase-product/list/`,
    GET_PURCHASE_PRODUCT_URL: `${API}/employee/api/v1/purchase-product/`,
  },
};
